apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dj9ggbbn0-nodejs
  janus-idp.io/tekton: dj9ggbbn0-nodejs
  backstage.io/kubernetes-id: dj9ggbbn0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dj9ggbbn0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
